# Generated by Django 4.1.3 on 2022-11-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subjecDescription',
            new_name='subjectDescription',
        ),
        migrations.AlterField(
            model_name='user',
            name='mobilenumber',
            field=models.CharField(default='', max_length=50),
        ),
    ]
